esphome:
  name: minimal-epaper-display

external_components:
  - source: github://semvis123/esphome-crowpanel-4.2-epaper@fix
    components: [ crowpanel_epaper ]

esp32:
  board: esp32-s3-devkitc-1

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: UART0

font:
  - file: "Roboto-Regular.ttf"
    id: roboto_regular
    size: 20
  
  - file: "Roboto-Regular.ttf"
    id: large_font
    size: 36
    
  - file: "Roboto-Regular.ttf"
    id: small_font
    size: 16
    
  - file: "materialdesignicons-webfont.ttf"
    id: icon_font
    size: 50
    glyphs:
      - "\U000F01E7" # earth icon

globals:
  - id: simple_counter
    type: int
    restore_value: no
    initial_value: '1'

display:
  - platform: crowpanel_epaper
    clk_pin: 12
    mosi_pin: 11
    id: epaper_display
    model: 4.20in 
    cs_pin: 45
    dc_pin: 46
    reset_pin: 47
    busy_pin: 48
    update_interval: 5s
    full_update_every: 10
    rotation: 180
    lambda: |-
      it.printf(it.get_width()/2, it.get_height()/2, id(large_font), Color::BLACK, TextAlign::CENTER, "Hello World!");
      it.printf(it.get_width()/2, it.get_height()/4, id(icon_font), Color::BLACK, TextAlign::CENTER, "\U000F01E7");
      it.printf(it.get_width()/2, 3*it.get_height()/4, id(roboto_regular), Color::BLACK, TextAlign::CENTER, "Counter: %d", id(simple_counter));
      id(simple_counter) += 1;

switch:
  - platform: gpio
    pin: 7
    id: epd_power
    name: "EPD Power"
    restore_mode: ALWAYS_ON